### ISSUE TITLE
HI absorption in simulations with radiative transfer 

### ISSUE THREAD

**Issue by Anikbh11** [trident-project/trident#111]
Hey! 

I have a question about generating spectra (specially HI) in simulations that have radiative transfer (RT). Currently from what I understand, trident uses cloudy Ion balance tables to calculate the ionization balance. Can I use the neutral hydrogen fractions (RT outputs) that are stored in the simulation files to calculate the ion fields/spectra? There can be a significant difference in the spectra (RT vs Ion balance). 

Thanks, 
Aniket

**Comment by brittonsmith** [comment]
Hi Aniket,

Yes, this is possible. All that is required is for you to be able to create a field called `H_p0_number_density`, representing the neutral H number density. If that field exists, it will be stored within the light ray and used to make spectra. The ion balance fields will only be made if a field with that name doesn't exist. If you have a stored field representing neutral H fraction, then you can [create a derived field in yt](https://yt-project.org/docs/dev/developing/creating_derived_fields.html). Let me know if you have any more questions about this.

Britton

**Comment by Anikbh11** [comment]
Hi Britton, 

Thanks for your response, I tried making a derived field using the neutral H fraction that is stored in the simulations. It works perfectly, thanks a lot! 

If you don't mind, I have some followup questions : 

- Based off the dl values in the light ray produced (ray.all_data()), the bins aren't uniform. Once I convert the ray to an absorption spectrum, it will be uniformly binned in lambda or velocity space based on the resolution (dlambda) I provide. Can I output the fields stored in the ray (temperature, N_HI etc.) as a function of the velocity bins as in the absorption spectrum?

- I want to use the N_HI values to calculate the 21 cm optical depths, which doesn't include doppler broadening. Can I disable the voigt broadening while calculating the absorption spectra? The other way would be to use the field values in each velocity bin to calculate tau, which is the main reason behind my first question. 

- I'm using a small box (12.5 cMpc) and I want to loop my sightlines inside the same box multiple times to get a fixed sightline length (say ~10x boxsize). As I understand I'll have to use the compound ray feature by setting Max_box_fraction to 10. Is this the right approach? 

Thanks,
Aniket

**Comment by chummels** [comment]
The original question was answered.  The followup question is being addressed by PR #128.  So I'm closing this.
