### ISSUE TITLE
images in docs are broken

### ISSUE THREAD

**Issue by brittonsmith** [trident-project/trident#146]
In the latest build of the trident docs on readthedocs, the images from trident-project.org urls are broken. I suggest moving these to the [trident-docs-images](https://github.com/trident-project/trident-docs-images) repo I set up. A few of the docs images are in there now, but only the new ones I added last year.

**Comment by chummels** [comment]
I don't see where there are missing images in the docs.  Can you please point me to where that happened?  It's also a bit confusing, as those URLs are fixed so I don't see how this could potentially even happen unless the domain goes down.
