### ISSUE TITLE
Stable version of code is broken

### ISSUE THREAD

**Issue by chummels** [trident-project/trident#180]
Due to some changes in yt, our primary dependency, moving the location of the `yt.load()` command around, the current stable version of trident is broken.  I cannot release a stable version of the code until a similar stable release occurs for the `yt_astro_analysis` code, which it looks like may not have happen for a while.  I'm sorry to everyone, but this will be addressed as soon as possible. 

For now, the solution is to get the development version of the code, see: https://trident.readthedocs.io/en/latest/installation.html#installing-the-development-version-of-yt-and-trident

For more about this issue, see: https://github.com/yt-project/yt_astro_analysis/issues/86

**Comment by neutrinoceros** [comment]
update:
- yt_astro_analysis 1.1 has been released and is compatible with yt 4.0

> our primary dependency, moving the location of the yt.load() command around, the current stable version of trident is broken. 

actually I think this is trivial to fix in a backward compatible way in trident by simply replacing `from yt.convenience import load` by `from yt import load`.
Are there any other known incompatibilities preventing a release ?
