### ISSUE TITLE
Make it clearer that bitbucket repo is deprecated

### ISSUE THREAD

**Issue by ngoldbaum** [trident-project/trident#22]
For yt we did this by going into the settings for the repo and making the wiki the landing page, then adding a front-page entry to the wiki saying that the project moved to github.

**Comment by chummels** [comment]
Have updated the Bitbucket repo with clear info that we've now moved to Github.  Thanks for the note, @ngoldbaum !

https://bitbucket.org/trident-project/trident/wiki/Home
