### ISSUE TITLE
Add progress bars for initial setup

### ISSUE THREAD

**Issue by ngoldbaum** [trident-project/trident#23]
Right now there are some long pauses in the initial setup process (especially on a slow network). Should add progress bars for the various setup stages so it's clearer that python isn't hanging.

**Comment by chummels** [comment]
When you say initial setup, what do you mean?  We've got progress bars on the file downloads during the initial setup.  I thought the main time-consuming part was the yt install, and that has progress bars.  Maybe it's the datasets being downloaded so you can run the tests?

**Comment by ngoldbaum** [comment]
I'm specifically referring to this part:

```
Using /Users/goldbaum/.trident

The following data files are available:
1) hm2012_hr.h5.gz   296 MB   Haardt Madau 2012 Background High Res (Preferred)
2) hm2012_lr.h5.gz    42 MB   Haardt Madau 2012 Background Low Res
3) fg2009_hr.h5.gz   262 MB   Faucher-Giguere 2009 Background High Res
4) fg2009_lr.h5.gz    37 MB   Faucher-Giguere 2009 Background Low Res

Which number would you like to download and use? [1]

<long pause>
  Unzipping file: hm2012_hr.h5.gz
```
Where I've editorially inserted `<long pause>` into the place that seems to hang.

**Comment by chummels** [comment]
Weird.  I thought I had a progress bar for the download.  OK, we can try to fix this.  Thanks for the feedback.

**Comment by chummels** [comment]
Weird, when I run that step, I get a full progress bar as it downloads.  I guess I may have a package installed that you do not, and it is failing silently.

`No ion table data file found in /Users/chummels/.trident
The following data files are available:
1) hm2012_hr.h5.gz   296 MB   Haardt Madau 2012 Background High Res (Preferred)
2) hm2012_lr.h5.gz    42 MB   Haardt Madau 2012 Background Low Res
3) fg2009_hr.h5.gz   262 MB   Faucher-Giguere 2009 Background High Res
4) fg2009_lr.h5.gz    37 MB   Faucher-Giguere 2009 Background Low Res

Which number would you like to download and use? [1]
1

Downloading file: hm2012_hr.h5.gz: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 302357.5498046875/302357.5498046875 [00:19<00:00, 15334.58it/s]
  Unzipping file: hm2012_hr.h5.gz
>>>`

**Comment by chummels** [comment]
I'll find the package and make sure it gets installed with trident in our pip requirements.

**Comment by chummels** [comment]
That's odd.  We're using yt's own pbar, which I assume you should have installed already.

https://github.com/trident-project/trident/blob/master/trident/utilities.py#L111

I wonder why it didn't work for you.

**Comment by ngoldbaum** [comment]
Oh I see, you're using yt's progress bar code, which my yt configuration is disabling.

You may want to think about not relying on yt for that and just depending on e.g. `tqdm` (https://github.com/tqdm/tqdm) to avoid cross-project issues. That said it's probably a rare issue so if you don't feel like messing with this it's probably not worth focusing on.

**Comment by ngoldbaum** [comment]
Just keep in mind that we're not explicitly exposing the utilities in yt.funcs as part of the public API so they're subject to change in the future. Both in terms of API and functionality. If you're ok with managing that risk then it's fine but something to keep in mind.

I'm personally not a fan of how much logging output yt generates so I supress it using the `suppressStreamLogging` configuration option. It turns out that also suppressed the progress bars.

**Comment by chummels** [comment]
I think I'm OK with managing the risk that associated with the internal API changing to the progress bar stuff in yt.  If that API changes, it will break our tests, and we'll deal with it as it comes.  I think there are a minimum number of people who suppress logging in yt, and they know what they're getting into by doing so, so I'm going to close this issue for now.
