### ISSUE TITLE
Fix Astropy Deprecation

### ISSUE THREAD

**Issue by chummels** [trident-project/trident#4]
When running the tests, we get this warning from astropy.  We should fix this so no warnings.

`tests/test_absorption_spectrum.py::AbsorptionSpectrumTest::test_absorption_spectrum_fits
  /Users/chummels/src/yt-conda/lib/python3.6/site-packages/astropy/utils/decorators.py:482: AstropyDeprecationWarning: "clobber" was deprecated in version 2.0 and will be removed in a future version. Use argument "overwrite" instead.
    AstropyDeprecationWarning)`

**Comment by brittonsmith** [comment]
Resolved in [PR 13](https://github.com/trident-project/trident/pull/13).
