### ISSUE TITLE
trident.add_ion_fields and particle filter doesn't work together

### ISSUE THREAD

**Issue by qobilidop** [trident-project/trident#41]
I'm using yt-4.0 and Trident sph-viz branch.

To trigger the issue:
```python
import trident
import yt

@yt.particle_filter(requires=['radial_velocity'], filtered_type='gas')
def outflow(pfilter, data):
    return data[pfilter.filtered_type, 'radial_velocity'] > 0

ds = yt.load('FIRE_M12i_ref11/snapshot_600.hdf5')
trident.add_ion_fields(ds, 'C')
ds.add_particle_filter('outflow')
```
which results in:
```
Traceback (most recent call last):
  File "test.py", line 10, in <module>
    ds.add_particle_filter('outflow')
  File "/Users/qobilidop/project/dev/yt/yt/data_objects/static_output.py", line 695, in add_particle_filter
    used = self._setup_filtered_type(f)
  File "/Users/qobilidop/project/dev/yt/yt/data_objects/static_output.py", line 730, in _setup_filtered_type
    fd[filter.name, fn[1]] = fd[fn]
KeyError: ('gas', 'C_p0_density')
```
Somehow `'C_p0_density'` is not in `fd = self.field_dependencies`, while all the other fields like `'C_density'`, `'C_p1_density'`, and `'C_p2_density'` are in `fd`. This might have something to do with how the aliasing field `'C_density'` is created in Trident.

One hack solution I've tried is to replace
```python
fd[filter.name, fn[1]] = fd[fn]
```
(see [this line](https://github.com/yt-project/yt/blob/e4d7fbf279df5ba522af58d3f860a70832254350/yt/data_objects/static_output.py#L730) for the context), by
```python
if fn in fd:
    fd[filter.name, fn[1]] = fd[fn]
```
Although this seems to work for my application, I'm not sure if it has no side effect.

**Comment by chummels** [comment]
Yeah, the alias fields for the neutral ions  (i.e., `C_p0_density` mapping to `C_density`) has always been a big of a kluge and has problems once in a while.  I guess we'll have to dig into explicitly adding the aliased field to the `field_dependencies`.  I don't see a problem with what you're doing here, but if others have more insight on this problem or solution, please chime in!

**Comment by chummels** [comment]
I tested out the sample script on the tip of trident + yt and everything works OK now.
