### ISSUE TITLE
Fix yt deprecation warnings

### ISSUE THREAD

**Issue by chummels** [trident-project/trident#5]
When we run the tests (or anything involving adding ion fields), we get a deprecation warning regarding the `sampling_type`.  This is because yt used to use `particle_type=bool`, which we copied, but then it switched to having this `sampling_type` kwarg.  We need to modify our own integration to use the appropriate `sampling_type` instead of just using `particle_type` internally.

```
tests/test_ion_balance.py::test_add_ion_fraction_field_to_grid_ds
  /Users/chummels/trident/trident/ion_balance.py:394: UserWarning: Because 'sampling_type' not specified, yt will assume a cell 'sampling_type'
    force_override=force_override)
```

**Comment by brittonsmith** [comment]
Resolve in [PR 13](https://github.com/trident-project/trident/pull/13).
