### ISSUE TITLE
make_onezone_ray() function broken in sph-viz branch

### ISSUE THREAD

**Issue by chummels** [trident-project/trident#76]
The nice utility `make_onezone_ray()` is for creating a ray with a single absorber element on it.  This works fine in the `master` branch with the tip of yt's dev branch.  However, there is a problem with the `yt-4.0` branch.  The problem appears to be due to how `yt` reads in datasets saved with the `save_as_dataset()` function, not a problem in trident per se.

When `make_onezone_ray()` runs, it creates a `LightRay` object with its various fields and a single element array in each field (e.g., `temperature`, `metallicity`, etc.)  This gets saved to disk as `ray.h5` using the `save_as_dataset()` function in yt.  Upon inspection, this file is correct and possesses all the necessary fields with a single element in each array.  However, when this dataset is loaded again by yt using the `load()` command, the fields are present, but all of them are empty.  Not sure what is going on, but this seems indicative of a larger problem, potentially in yt.  

Oddly enough, this does *not* affect rays that are generated by the standard means `make_simple_ray()` for actual datasets, or we would've caught it with the tests.

```
import yt
import trident
import h5py as h5
ray = trident.make_onezone_ray(filename='ray_test.h5')
f = h5.File('ray_test.h5', 'r')
print("HDF5 file shows this temperature field: ", list(f['grid/temperature']))
f.close()
ds = yt.load('ray_test.h5')
print("yt shows this temperature field: ", ds.r['temperature'])
```

returns:

```
HDF5 file shows this temperature field:  [1000.0]                                                                      
yt shows this temperature field:  [] K
```

**Comment by chummels** [comment]
I'm not sure what happened in the intervening year, but this bug has been fixed, presumably with some recent change in the yt-4.0 branch.  You can confirm this by running the test script and seeing that it now returns: 

```
HDF5 file shows this temperature field:  [1000.0]                                                                      
yt shows this temperature field:  [1000.] K
```

Since it is fixed, I'm closing it.

**Comment by brittonsmith** [comment]
I had to think about it for a minute, but this was a yt bug. A small bug crept in to data selection from `ytdata` datasets. I can't remember exactly what it was, a units thing or something, but it being on the yt side is probably why I forgot to close this.
