### ISSUE TITLE
Annotation of trident ray not working for uniform data

### ISSUE THREAD

**Issue by maxbeegee** [trident-project/trident#79]
The example shown on the webpage does not fully work for me (using a uniform grid data set).
In particular, the annotation of the ray does not function properly.

This is not a big deal, I was just wondering why this is. 

See minimal example below.

```python
import yt
import numpy as np
import trident

def generate_ds():
    arr = np.random.random(size=(64,64,64))
    data = dict(density = (arr, "g/cm**3"), temperature = (arr,'K'))
    for k in "xyz":
        data['velocity_' + k] = (arr, 'cm/s')
    bbox = np.array([[-1.5, 1.5], [-1.5, 1.5], [-1.5, 1.5]])
    ds = yt.load_uniform_grid(data, arr.shape, length_unit="Mpc", bbox=bbox, nprocs=64)

    return ds


def test_trident_mwe():
    ds = generate_ds()
    ray_start = ds.domain_left_edge
    ray_end = ds.domain_right_edge

    line_list = ['H']
    ray = trident.make_simple_ray(ds,
                                  start_position=ray_start,
                                  end_position=ray_end,
                                  data_filename="mwe_ray.h5",
                                  lines=line_list,
                                  ftype='stream')

    p = yt.ProjectionPlot(ds, 'x', 'density')
    p.annotate_ray(ray, arrow=True) # not working

    # This is working
    ray2 = ds.ray(ds.domain_left_edge, ds.domain_right_edge)
    p.annotate_ray(ray2, arrow=True, plot_args = {'color' : 'red', 'ls' : '--'}) 

    p.save('mwe_projection.png')

if __name__ == '__main__':
    test_trident_mwe()

```

**Comment by chummels** [comment]
Hi @maxbeegee .  I tested out your script and it works fine for me.  When I comment out the explicit `ds.ray()` section and *only* rely on the section you have listed as "not working", it still annotates the ray's path on the projection.  

What version of the code are you using?  I'm using the `yt-4.0` branch of yt and the `sph-viz` version of trident.  For more info on this version, see: https://nbviewer.jupyter.org/url/trident-project.org/notebooks/trident_demesh_install.ipynb

I hope this helps!

**Comment by maxbeegee** [comment]
For completeness: I am using trident 1.1 and yt 3.6...so probably not worth fixing this bug.

**Comment by chummels** [comment]
I have tested this out on the tip of yt+trident and it works OK.  I'm putting out a new stable version of trident imminently that is based on the dev branch, so this problem won't be an issue in neither stable nor dev trident.
